# SPDX-FileCopyrightText: 2025 Madeline Baggins <madeline@baggins.family>
#
# SPDX-License-Identifier: GPL-3.0-only

[package]
name = "maddi-recipe"
version = "0.1.0"
edition = "2024"

[dependencies]
